server {
    listen 80;
    server_name semibrain.net.cn www.semibrain.net.cn;
    return 308 https://semibrain.net.cn$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name www.semibrain.net.cn;
    ssl_certificate /etc/nginx/tls/fullchain.pem;
    ssl_certificate_key /etc/nginx/tls/semibrain.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    return 308 https://semibrain.net.cn$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name semibrain.net.cn;
    ssl_certificate /etc/nginx/tls/fullchain.pem;
    ssl_certificate_key /etc/nginx/tls/semibrain.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    client_max_body_size 34m;
    resolver 127.0.0.11 valid=5s ipv6=off;
    set $web_upstream http://web:8080;
    location / {
        proxy_pass $web_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
        proxy_buffering off;
        proxy_read_timeout 240s;
    }
}
